#!/usr/bin/python

import subprocess
import sys

def compare_sorts(algorithms, count, size):
    avg = [0] * len(algorithms);
            
    alg_exec = "./" + alg + " -f 2 -s " + size;
    for j, alg in enumerate(algorithms):
        time = 0;
        for _ in range(count):
            p = subprocess.Popen(alg_exec, shell = True, stdout = subprocess.PIPE);
            time += float(((p.stdout.read()).decode("utf-8")).split(" ")[2]);

        avg[j] = time / count;

    return avg;


if __name__ == "__main__":
    length = len(sys.argv);
    if(length == 1):
        sys.exit('./comp list_count list_size alg1 alg2 ... algn');


    algorithms = sys.argv[3:length];

    count = int(sys.argv[1]);
    size = sys.argv[2];

    avg = compare_sorts(algorithms, count, size);

    alg_name_length = [len(alg) for alg in algorithms];

    max_length = max(alg_name_length);

    for alg, l, a in zip(algorithms, alg_name_length, avg):
        padding = max_length - l;
        print(alg + ": " + " " * padding + str(a));
