#!/usr/bin/python

import matplotlib.pyplot
import subprocess
import sys

def get_hist(count, size, bins, alg):
    alg_exec = "./" + alg + " -f 2 -s " + str(size);
    time = [None] * count;
    for i in range(count):
        p = subprocess.Popen(alg_exec, shell = True, stdout = subprocess.PIPE);
        time[i] = float(((p.stdout.read()).decode("utf-8")).split(" ")[2]);

    matplotlib.pyplot.hist(time, bins=bins, density=True);
    
        

if __name__ == "__main__":
    if(len(sys.argv) < 5):
        sys.exit("./histogram count size bins alg1 alg2 alg3 ... algN");

    count, size, bins = map(int, sys.argv[1:4]);

    #count = int(sys.argv[1]);
    #size = int(sys.argv[2]);
    #bins = int(sys.argv[3]);

    fig = matplotlib.pyplot.figure();

    for alg in sys.argv[4:]:
        get_hist(count, size, bins, alg);

    matplotlib.pyplot.xlabel("time");
    matplotlib.pyplot.ylabel("counts");
    matplotlib.pyplot.show();



