#!/usr/bin/python

import subprocess
import sys
import numpy

def avg_comparison(alg, size, count, thread):
    comp = 0;

    alg_exec = "./" + alg + " -f 2 -s " + size + " -e " + thread;

    for _ in range(count):
        p = subprocess.Popen(alg_exec, shell = True, stdout = subprocess.PIPE);
        out_s = p.stdout.read().decode("utf-8");

        comp += float(out_s.split()[2]);

    return comp / count;
                                        

if __name__ == "__main__":
    if(len(sys.argv) == 1):
        sys.exit("./thread alg size count output_file left_range right_range step_size");

    alg = sys.argv[1];
    size = sys.argv[2]
    count = int(sys.argv[3]);
    outfile = sys.argv[4];

    left = int(sys.argv[5]);
    right = int(sys.argv[6]);
    stepsize = int(sys.argv[7]);

    step = int((right - left) / stepsize) + 1;

    with open(outfile, "w+") as fp:
        for thread_count in numpy.linspace(left, right, step):
            avg = avg_comparison(alg, size, count, str(int(thread_count)));
            fp.write(str(int(thread_count)) + " " + str(avg) + "\n");
                                                                                                                
