#!/usr/bin/python

import subprocess
import sys


if __name__ == "__main__":
    if(len(sys.argv) == 1):
        sys.exit("./verify alg count");

    if(len(sys.argv) == 3):
        print("Two arguments required.");
        sys.exit("./verify alg count");

    alg = sys.argv[1];
    count = int(sys.argv[2]);

    sizes = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 100, 1000};

    tally = [0] * len(sizes);

    for i, size in enumerate(sizes):
        for x in range(0, count):
            p = subprocess.Popen(["./" + alg + " -f 4 -s " + str(size)], shell = True, stdout = subprocess.PIPE);
            out = (p.stdout.read()).decode("utf-8");

            if out:
                tally[i] += 1;


    for i, size in enumerate(sizes):
        if tally[i] != 0 :
            print(str(size) + "failed" + str(tally[i]) + "times");

    total = sum(tally);
    if total != 0:
        print("Total failed sorts: " + str(total));
    else:
        print("No failed sorts.");
