#!/usr/bin/python

import subprocess
import sys


if __name__ == "__main__":
    if(len(sys.argv) == 1):
        sys.exit("./verify alg [count]");

    alg = sys.argv[1];

    count = 10;

    if(len(sys.argv) == 3):
        count = int(sys.argv[2]);

    sizes = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 100, 1000};

    tally = [0] * len(sizes);

    for i, size in enumerate(sizes):
        alg_exec = "./" + alg + " -f 4 -s " + str(size);
        for _ in range(count):
            p = subprocess.Popen(alg_exec, shell = True, stdout = subprocess.PIPE);
            out = (p.stdout.read()).decode("utf-8");

            if out:
                tally[i] += 1;
                print(str(size) + " failed.");


    for tal, size in zip(tally, sizes):
        if tal != 0:
            print(str(size) + " failed " + str(tal) + " times.");

    total = sum(tally);

    if total != 0:
        str_out = "Total failed sorts: " + str(total);

    else:
        str_out = "No failed sorts.";

    print(str_out);
